import { Palette } from "std-widgets.slint";

export component AlertWindow inherits Rectangle {
    property <string> alert_msg;
    property <string> alert_msg_intern;
    property <length> offset: 500px;

    animate offset { duration: 300ms; }

    public function alert(msg: string) {
        alert_msg = msg;
        timer.running = true;
        self.offset = 0;
    } 
    
    timer := Timer {
        interval: 3s;
        running: false;
        triggered() => {
            root.offset = 500px;
            self.running = false;
        }
    } 

    Rectangle {
        border-radius: 10px;
        background: Palette.background;
        drop-shadow-blur:  5px;
        drop-shadow-color: rgba(0, 0, 0, 0.2);
        drop-shadow-offset-x: 5px;
        drop-shadow-offset-y: 5px;
        x: root.offset;
        Text {
            x: 10px;
            y: root.height / 2 - self.height / 2;
            width: parent.width - 10px;
            text: root.alert_msg;
            font-size: 20px;
            color: Palette.control-foreground;
            wrap: word-wrap;
        }
    }
}