import { CardsDisplay } from "cards-display.slint";
import {
    CardSuitSlint,
    CardRankSlint,
    CardSlint,
    PlayerSlint,
    AppState,
    CardTextures,
} from "structs.slint";
import { HomeScreen } from "home-screen.slint";
import { PlayersDisplay } from "player-display.slint";
import { PendingGame } from "pending-game-screen.slint";
import { TableCardsDisplay } from "table-display.slint";
import { Hotbar } from "hotbar.slint";
import { LoginWindow } from "login-window.slint";
import { GameOverScreen } from "game-over.slint";
import { AlertWindow } from "alert-window.slint";
import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    //height: 1000px;
    //width: 570px;
    title: "Skat-Game";

    in-out property <bool> my_turn: false;
    in-out property <AppState> app_state;

    public function alert(msg: string) {
        alert_window.alert(msg);
    }

    Rectangle {
        background: @radial-gradient(circle, #007400 0%, #004400 100%);
    }

    //this is image forces the CardTextures to pre-load
    Image {
        x: 10000px;
        source: CardTextures.card_to_image({ suit: CardSuitSlint.clubs, rank: CardRankSlint.Ace });
    }

    in-out property <[CardSlint]> table_cards;
    if (app_state == AppState.Game): HorizontalLayout {
        alignment: center;
        TableCardsDisplay {
            cards: root.table_cards;
            card_width: root.width / 3;
            y: root.height * 20%;
        }
    }

    in-out property <[CardSlint]> hand;
    callback set_position(from: int, to: int);
    callback play_card(card: CardSlint);
    if (app_state == AppState.Game || app_state == AppState.Bid): CardsDisplay {
        hand: hand;
        play_card(card) => {
            if (app_state == AppState.Game && my_turn) {
                root.play_card(card);
            }
        }
        set_position(from, to) => {
            root.set_position(from, to);
        }
    }

    in property <string> game_value: "0";
    in property <CardSuitSlint> game_trump: CardSuitSlint.none;
    in-out property <bool> select_trump: false;
    callback pass;
    callback bid_further;
    callback selected_trump(suit: CardSuitSlint);
    if (app_state == AppState.Game || app_state == AppState.Bid): Hotbar {
        height: parent.height * 15%;
        y: parent.y + parent.height - self.height;
        pass => {
            my_turn = false;
            root.pass();
        }
        bid_further => {
            root.bid_further();
        }
        selected_trump(suit) => {
            root.selected_trump(suit);
            root.select_trump = false;
        }
        app_state: root.app_state;
        game_value: root.game_value;
        select_trump: root.select_trump;
        game_trump: root.game_trump;
        my_turn: root.my_turn;
    }

    callback join_game;
    if (app_state == AppState.Lobby || app_state == AppState.Login): HomeScreen {
        clicked => {
            root.join_game();
        }
    }

    callback add_npc;
    if (app_state == AppState.PendingGame): PendingGame {
        add_npc => {
            root.add_npc();
        }
    }

    in property <string> name;
    in property <[PlayerSlint]> players;
    if (app_state != AppState.Login): PlayersDisplay {
        x: 0;
        y: 0;
        width: max(root.width * 30%, 200px);
        players: root.players;
        self-name: root.name;
    }

    in property <int> points;
    callback return_to_lobby;
    if (app_state == AppState.GameLoose || app_state == AppState.GameWin || app_state == AppState.GameTie): GameOverScreen {
        clicked => {
            root.return_to_lobby();
        }
        app_state: root.app_state;
        points: root.points;
    }

    alert_window := AlertWindow {
        height: 100px;
        width: 400px;
        x: root.width - self.width - 10px;
        y: root.height - self.height - 10px;
    }

    if (app_state == AppState.Game || app_state == AppState.Bid || app_state == AppState.PendingGame): Button {
        icon: @image-url("textures/back_to_lobby.png");
        height: 50px;
        width: 50px;
        x: root.width - self.width - 5px;
        y: 5px;
        clicked => {
            root.return_to_lobby();
        }
    }

    callback submit_name(name: string);
    if (app_state == AppState.Login): LoginWindow {
        width: 70%;
        height: 40%;
        submit_name(name) => {
            root.submit_name(name);
        }
    }
}
