import { VerticalBox, Button, Palette } from "std-widgets.slint";

enum CardSuit { clubs, diamond, heart, spade }
enum CardRank { Seven, Eight, Nine, Ten, Jack, Queen, King, Ace }

struct Card {
    rank: CardRank,
    suit: CardSuit,
}

component CardDisplay inherits Rectangle {
    callback play_card(card: Card);
    callback set_position;
    callback start_pressed;

    in-out property <bool> press;
    in property <Card> card; 
    in property <image> icon;

    ta := TouchArea {
        clicked => {
            play_card(card);
        }
        moved => {
            set_position();
        }
        changed pressed => {
            start_pressed();
        }
    }

    press: ta.pressed;

    Rectangle {
        y: ta.has-hover ? -10px : 0px;
        animate y { duration: 50ms; }
        Rectangle {
            x: -5px;
            y: -5px;
            background: rgba(0, 0, 0, 0.2);
            border-radius: 10px;
        }

        Rectangle {
            width: parent.width;
            Image {
                x: 0px;
                y: 0px;
                source: icon;
                width: parent.width;
            }
            border-radius: 10px;
            clip: true;
        }
    }
}

export component MainWindow inherits Window {
    callback play_card(card: Card);
    callback set_position(from: int, to: int);
    callback submit_name(name: string);
    
    in-out property<[Card]> hand;
    in property <bool> has-name;
    in property <string> name;

    //this is a bit cursed, but slint does not support non static strings as image source
    property <[image]> card_images: [
        @image-url("textures/clubs_seven.png"),
        @image-url("textures/clubs_eigth.png"),
        @image-url("textures/clubs_nine.png"),
        @image-url("textures/clubs_ten.png"),
        @image-url("textures/clubs_jack.png"),
        @image-url("textures/clubs_queen.png"),
        @image-url("textures/clubs_king.png"),
        @image-url("textures/clubs_ace.png"),

        @image-url("textures/diamond_seven.png"),
        @image-url("textures/diamond_eigth.png"),
        @image-url("textures/diamond_nine.png"),
        @image-url("textures/diamond_ten.png"),
        @image-url("textures/diamond_jack.png"),
        @image-url("textures/diamond_queen.png"),
        @image-url("textures/diamond_king.png"),
        @image-url("textures/diamond_ace.png"),

        @image-url("textures/hearth_seven.png"),
        @image-url("textures/hearth_eigth.png"),
        @image-url("textures/hearth_nine.png"),
        @image-url("textures/hearth_ten.png"),
        @image-url("textures/hearth_jack.png"),
        @image-url("textures/hearth_queen.png"),
        @image-url("textures/hearth_king.png"),
        @image-url("textures/hearth_ace.png"),

        @image-url("textures/spade_seven.png"),
        @image-url("textures/spade_eigth.png"),
        @image-url("textures/spade_nine.png"),
        @image-url("textures/spade_ten.png"),
        @image-url("textures/spade_jack.png"),
        @image-url("textures/spade_queen.png"),
        @image-url("textures/spade_king.png"),
        @image-url("textures/spade_ace.png"),
    ];
    
    pure function card_to_image(card: Card) -> image {
        return card_images[suit_to_int(card.suit) * 8 + rank_to_int(card.rank) - 1];
    }

    pure function suit_to_int(suit: CardSuit) -> int {
        if suit == CardSuit.clubs { return 0; }
        else if suit == CardSuit.diamond { return 1; }
        else if suit == CardSuit.heart { return 2; }
        else { return 3; }
    }

    pure function rank_to_int(rank: CardRank) -> int {
        if rank == CardRank.Seven { return 1; }
        else if rank == CardRank.Eight { return 2; }
        else if rank == CardRank.Nine { return 3; }
        else if rank == CardRank.Ten { return 4; }
        else if rank == CardRank.Jack { return 5; }
        else if rank == CardRank.Queen { return 6; }
        else if rank == CardRank.King { return 7; }
        else { return 8; }
    } 

    Rectangle {
        background: @radial-gradient(circle, #007400 0%, #004400 100%);
    }

    Rectangle {
        height: 100px;
        width: 100px;
        x: 0;
        y: 0;
        background: rgb(255, 0, 0);
        transform-rotation: 45deg;
        transform-origin: {x: self.width / 2, y: self.height / 2};
    }

    property <length> mouseX;
    property <length> mouseY;

    ta := TouchArea {}
    mouseX: ta.mouse-x;
    mouseY: ta.mouse-y;

    for card[i] in hand : CardDisplay {
        height: 1000px;
        width: parent.width / 3;

        //x: self.press ? mouseX : parent.width / 2 - self.width / 2;
        //y: self.press ? mouseY : parent.height / 2; 

        x: parent.width / 2 - self.width / 2;
        y: parent.height / 2; 
        
        transform-rotation: (i - (hand.length / 2) + 1) * 0.5deg * parent.width / 100px;
        transform-origin: { x: self.width / 2, y: parent.height * 1.5 };

        icon: card_to_image(card);

        play_card => { play_card(card); }
        set_position => { set_position(i, 0)}
    } 

    property <string> input_text: "";

    if (!has-name) : Rectangle {
        width: 70%;
        height: 40%;
        border-radius: 10px;
        border-color: rgb(200, 200, 200);
        background: Palette.background;
        drop-shadow-blur:  5px;
        drop-shadow-color: rgba(0, 0, 0, 0.2);
        drop-shadow-offset-x: 5px;
        drop-shadow-offset-y: 5px;

        VerticalBox {
            x: parent.width * 10%;
            y: parent.height * 20%;
            width: 80%;
            height: 40px;

            input := TextInput { 
               color: Palette.control-foreground;
                edited => {
                    root.input_text = self.text;
                }
                   
            }
        }

        Text {
            x: parent.width * 10% + 7px;
            y: parent.height * 20% + 9px;
            text: "enter name";
            color: rgb(150, 150, 150);
            visible: root.input_text == "";
        }

        Button {
            x: parent.width * 10%;
            y: parent.height * 60%;
            width: 80%;
            height: 20%;
            text: "OK";
            clicked => root.submit_name(input.text);
        }
    }
}
