export { CardsDisplay }

import {
    CardSuitSlint,
    CardRankSlint,
    CardSlint,
    CardTextures,
} from "structs.slint";

component CardDisplay inherits Rectangle {
    callback play_card(card: CardSlint);
    callback set_position;
    callback start_pressed;

    in-out property <bool> press;
    in property <CardSlint> card;
    in property <image> icon;

    ta := TouchArea {
        clicked => {
            play_card(card);
        }
        //moved => { set_position(); }
        changed pressed => {
            start_pressed();
        }
    }

    press: ta.pressed;

    Rectangle {
        y: ta.has-hover ? -10px : 0px;
        animate y { duration: 50ms; }
        Rectangle {
            x: -5px;
            y: -5px;
            background: rgba(0, 0, 0, 0.2);
            border-radius: 10px;
        }

        Rectangle {
            width: parent.width;
            Image {
                x: 0px;
                y: 0px;
                source: icon;
                width: parent.width;
            }

            border-radius: 10px;
            clip: true;
        }
    }
}

component CardsDisplay inherits Rectangle {
    in-out property <[CardSlint]> hand;
    callback play_card(card: CardSlint);
    callback set_position(from: int, to: int);

    property <length> mouseX;
    property <length> mouseY;

    ta := TouchArea { }

    mouseX: ta.mouse-x;
    mouseY: ta.mouse-y;

    for card[i] in hand: CardDisplay {
        height: 500px;
        width: parent.width / 3;

        //x: self.press ? mouseX : parent.width / 2 - self.width / 2;
        //y: self.press ? mouseY : parent.height / 2;

        x: parent.width / 2 - self.width / 2;
        y: parent.height * 60%;

        transform-rotation: (i - (hand.length / 2) + 1) * 0.55deg * parent.width / 100px;
        transform-origin: { x: self.width / 2, y: parent.height * 80% };

        icon: CardTextures.card_to_image(card);

        play_card => {
            play_card(card);
        }
        set_position => {
            set_position(i, 0)
        }
    }
}
