import { AppState } from "structs.slint";
import { Button } from "std-widgets.slint";

export component GameOverScreen inherits Rectangle {
    callback clicked;
    in property <AppState> app_state;
    in property <int> points: 0;

    pure function img(state: AppState) -> image {
        if (state == AppState.GameWin) {
            return @image-url("textures/thumbs_up.png");
        }
        if (state == AppState.GameLoose) {
            return @image-url("textures/cat_laugh.jpg");
        }
        return @image-url("textures/tie.jpg");
    }

    Image {
        source: img(app_state);
        width: root.width * 80%;
        height: root.height * 80%;
        x: root.width * 10%;
        y: root.height * 10%;
    }

    pure function msg(state: AppState) -> string {
        if (state == AppState.GameWin) {
            return "You Won!";
        }
        if (state == AppState.GameLoose) {
            return "You Lost!";
        }
        return "It's a Tie!";
    }

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            spacing: 20px;

            Text {
                text: msg(app_state);
                font-size: 32px;
                color: white;
            }

            Text {
                text: "Points: " + points;
                font-size: 24px;
                color: white;
            }

            Text {
                text: "Click to return to Lobby";
                font-size: 18px;
                color: white;
            }
        }
    }

    Button {
        opacity: 0.0;
        height: parent.height;
        width: parent.width;
        clicked => {
            root.clicked();
        }
    }
}
