import { AppState } from "structs.slint";
import { Button } from "std-widgets.slint";

export component GameOverScreen inherits Rectangle {
    callback clicked;
    in property <AppState> app_state;
    in property <int> points: 0;

    if (app_state == AppState.GameWin) : Image {
        source: @image-url("textures/thumbs_up.png");
        width: root.width * 80%;
        height: root.height * 80%;
        x: root.width * 10%;
        y: root.height * 10%;
    }
    
    if (app_state == AppState.GameLoose) : Image {
        source: @image-url("textures/cat_laugh.jpg");
        width: root.width * 80%;
        height: root.height * 80%;
        x: root.width * 10%;
        y: root.height * 10%;
    }

    if (app_state == AppState.GameTie) : Image {
        source: @image-url("textures/tie.jpg");
        width: root.width * 80%;
        height: root.height * 80%;
        x: root.width * 10%;
        y: root.height * 10%;
    }

    HorizontalLayout { alignment: center; VerticalLayout {
        alignment: center;
        spacing: 20px; 

        if (app_state == AppState.GameWin) : Text {
            text: "You Won!";
            font-size: 32px;
            color: white;
        }

        if (app_state == AppState.GameLoose) : Text {
            text: "You Lost!";
            font-size: 32px;
            color: white;
        }

        if (app_state == AppState.GameTie) : Text {
            text: "It's a Tie!";
            font-size: 32px;
            color: white;
        }

        Text {
            text: "Points: " + points;
            font-size: 24px;
            color: white;
        }

        Text {
            text: "Click to return to Lobby";
            font-size: 18px;
            color: white;
        }
    }}

    Button {
        //visible: false;
        opacity: 0.0;
        height: parent.height;
        width: parent.width;
        clicked => { root.clicked(); }
    }
}