export { PlayersDisplay }

import { VerticalBox, Button, Palette } from "std-widgets.slint";
import { PlayerSlint } from "structs.slint";

component PlayerDP inherits Rectangle {
    property <length> radius: self.width * 15%;
    in property <bool> highlighted: false;
    in-out property <string> name;

    Rectangle {
        property <length> size-diff: 10px;
        x: radius;
        y: size-diff;
        height: (radius - size-diff) * 2;
        width: parent.width - radius - size-diff - self.height / 2;
        background: Palette.background;
        border-radius: self.height / 2;
        border-color: highlighted ? yellow : Palette.background;
        border-width: 2px;

        Text {
            x: radius + 5px;
            text: name;
            vertical-alignment: center;
            color: Palette.control-foreground;
            font-size: parent.height / 2;
        }
    }

    Rectangle {
        x: 0px;
        y: 0px;
        width: radius * 2;
        height: radius * 2;
        border-radius: radius;
        background: Palette.background;
        border-color: highlighted ? yellow : Palette.background;
        border-width: 2px;
    }

    Rectangle {
        property <length> radius-diff: 7px;
        x: radius-diff;
        y: radius-diff;
        width: (radius - radius-diff) * 2;
        height: (radius - radius-diff) * 2;
        border-radius: (radius - radius-diff);
        clip: true;
        Image {
            x: 0;
            y: 0;
            width: parent.width;
            height: parent.height;
            source: @image-url("textures/default_profile_pic.png");
        }
    }
}

component PlayersDisplay inherits Rectangle {
    in property <[PlayerSlint]> players;
    in property <int> has_turn_id;

    VerticalLayout {
        spacing: 10px;
        alignment: start;

        for player[i] in players: PlayerDP {
            name: player.name;
            preferred-height: root.width * 30%;
            highlighted: player.id == has_turn_id ? true : false;
        }
    }
}
