export { PlayersDisplay }

import { VerticalBox, Button, Palette } from "std-widgets.slint";
import { PlayerSlint } from "structs.slint";

component PlayerDP inherits Rectangle {
    property<length> radius: self.width * 15%;
    in-out property<string> name;

    Rectangle {
        property<length> size-diff: 10px;
        x: radius;
        y: size-diff;
        height: (radius - size-diff) * 2;
        width: parent.width - radius - size-diff - self.height / 2;
        background: Palette.background;

        Rectangle {
            property<length> litte-radius: parent.height / 2;
            background: Palette.background;
            x: parent.width - litte-radius;
            y: parent.height / 2 - litte-radius;
            border-radius: litte-radius;
            width: litte-radius * 2;
            height: litte-radius * 2;
        }

        Text {
            x: radius + 5px;
            text: name;
            vertical-alignment: center;
            color: Palette.control-foreground;
            font-size: parent.height / 2;
        }
    }

    Rectangle {
        x: 0px;
        y: 0px;
        width: radius * 2;
        height: radius * 2;
        border-radius: radius;
        background: Palette.background;
    }

    Rectangle {
        property<length> radius-diff: 7px;
        x: radius-diff;
        y: radius-diff;
        width: (radius - radius-diff) * 2;
        height: (radius - radius-diff) * 2;
        border-radius: (radius - radius-diff);
        clip: true;
        Image {
            x: 0;
            y: 0;
            width: parent.width;
            height: parent.height;
            source: @image-url("textures/default_profile_pic.png");
        }
    }
}

component PlayersDisplay inherits Rectangle {
    in property<[PlayerSlint]> players;
    in property<string> self-name;

    VerticalLayout {
        spacing: 10px;
        alignment: start;

        PlayerDP {
            transform-scale: 115%;
            transform-origin: { x: 10px , y: 0 };
            name: root.self-name;
            preferred-height: root.width * 35%;
        }

        for player[i] in players : PlayerDP {
            name: player.name;
            preferred-height: root.width * 30%;
        }
    }
}

