export enum CardSuitSlint { clubs, diamond, heart, spade, none}
export enum CardRankSlint { Seven, Eight, Nine, Ten, Jack, Queen, King, Ace }
export enum AppState { Login, Lobby, PendingGame, Bid, Game }

export struct CardSlint {
    rank: CardRankSlint,
    suit: CardSuitSlint,
}

export struct PlayerSlint {
    name: string,
    id: int,
}

export component CardTextures  {
    //this is a bit cursed, but slint does not support non static strings as image source
    property <[image]> card_images: [
        @image-url("textures/clubs_seven.png"),
        @image-url("textures/clubs_eigth.png"),
        @image-url("textures/clubs_nine.png"),
        @image-url("textures/clubs_ten.png"),
        @image-url("textures/clubs_jack.png"),
        @image-url("textures/clubs_queen.png"),
        @image-url("textures/clubs_king.png"),
        @image-url("textures/clubs_ace.png"),

        @image-url("textures/diamond_seven.png"),
        @image-url("textures/diamond_eigth.png"),
        @image-url("textures/diamond_nine.png"),
        @image-url("textures/diamond_ten.png"),
        @image-url("textures/diamond_jack.png"),
        @image-url("textures/diamond_queen.png"),
        @image-url("textures/diamond_king.png"),
        @image-url("textures/diamond_ace.png"),

        @image-url("textures/hearth_seven.png"),
        @image-url("textures/hearth_eigth.png"),
        @image-url("textures/hearth_nine.png"),
        @image-url("textures/hearth_ten.png"),
        @image-url("textures/hearth_jack.png"),
        @image-url("textures/hearth_queen.png"),
        @image-url("textures/hearth_king.png"),
        @image-url("textures/hearth_ace.png"),

        @image-url("textures/spade_seven.png"),
        @image-url("textures/spade_eigth.png"),
        @image-url("textures/spade_nine.png"),
        @image-url("textures/spade_ten.png"),
        @image-url("textures/spade_jack.png"),
        @image-url("textures/spade_queen.png"),
        @image-url("textures/spade_king.png"),
        @image-url("textures/spade_ace.png"),
    ];

    public pure function card_to_image(card: CardSlint) -> image {
        return card_images[suit_to_int(card.suit) * 8 + rank_to_int(card.rank) - 1];
    }

    pure function suit_to_int(suit: CardSuitSlint) -> int {
        if suit == CardSuitSlint.clubs { return 0; }
        else if suit == CardSuitSlint.diamond { return 1; }
        else if suit == CardSuitSlint.heart { return 2; }
        else { return 3; }
    }

    pure function rank_to_int(rank: CardRankSlint) -> int {
        if rank == CardRankSlint.Seven { return 1; }
        else if rank == CardRankSlint.Eight { return 2; }
        else if rank == CardRankSlint.Nine { return 3; }
        else if rank == CardRankSlint.Ten { return 4; }
        else if rank == CardRankSlint.Jack { return 5; }
        else if rank == CardRankSlint.Queen { return 6; }
        else if rank == CardRankSlint.King { return 7; }
        else { return 8; }
    }
}